rm chaincash.aux
rm chaincash.out
rm chaincash.log
rm chaincash.bbl
rm chaincash.blg
pdflatex chaincash
bibtex chaincash
pdflatex chaincash
pdflatex chaincash
rm chaincash.aux
rm chaincash.out
rm chaincash.log
rm chaincash.bbl
rm chaincash.blg
